spring.application.name=SchoolSys

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=school
spring.jpa.properties.hibernate.format_sql=true

# DB
# Database Connection Settings
spring.datasource.url=jdbc:postgresql://ep-ancient-tooth-amfsy2cz-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require&currentSchema=school
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

# PostgreSQL Driver Class
spring.datasource.driver-class-name=org.postgresql.Driver